name: virtualenv
channels:
  - conda-forge
  - bioconda
dependencies:
# languages
  - python=3.8
  - r-base=4.2
  - gxx_linux-64==11.1.0

# r-packages
## CRAN
  - r-ggplot2
  - r-tidyverse
  - r-reticulate
  - r-scales
  - r-seurat
  - r-rcolorbrewer
  - r-wesanderson
  - r-jpeg
  - r-rjson
  - r-torch
#  - r-Luz #luz is not on anaconda... <sad face>
  - r-cowplot
  - r-matrix
  - r-lowrankqp # NEEDS R-4.2
  - r-igraph
  - r-umap
  - r-irlba

## BioConductor
#  - bioconductor-hdf5array
#  - bioconductor-rhdf5
#  - bioconductor-scuttle
#  - bioconductor-rhdf5lib
#  - bioconductor-dropletutils
#  - bioconductor-iranges
#  - bioconductor-summarizedexperiment




# python libraries
  - pip
  - pip:
    - certifi==2022.9.24
    - chardet==5.0.0
    - charset-normalizer==2.1.1
    - cheMLearning==0.0.1
    - contourpy==1.0.6
    - cycler==0.11.0
    - docker==6.0.1
    - entrypoints==0.4
    - escapism==1.0.1
    - fonttools==4.38.0
    - GMM-Demux==0.0.1
    - idna==3.4
    - iso8601==1.1.0
    - Jinja2==3.1.2
    - joblib==1.2.0
    - jupyter-repo2docker==2022.10.0
    - kiwisolver==1.4.4
    - MarkupSafe==2.1.1
    - matplotlib==3.6.2
    - nbconvert==6.5.0
    - numpy==1.23.5
    - packaging==21.3
    - pandas==1.5.2
    - Pillow==9.3.0
    - plotly==5.11.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - python-json-logger==2.0.4
    - pytz==2022.6
    - requests==2.28.1
    - ruamel.yaml==0.17.21
    - ruamel.yaml.clib==0.2.7
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - semver==2.13.0
    - six==1.16.0
    - tenacity==8.1.0
    - threadpoolctl==3.1.0
    - toml==0.10.2
    - traitlets==5.6.0
    - urllib3==1.26.13
    - websocket-client==1.4.2
    - xlrd==2.0.1
    
